version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: ia-gov-suite-postgres
    environment:
      POSTGRES_USER: iagov_user
      POSTGRES_PASSWORD: iagov_pass
      POSTGRES_DB: iagov_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: